### ISSUE TITLE
openwert serverspec should ignore all host keys during autoflash

### ISSUE THREAD

**Issue by sarcasticadmin** [socallinuxexpo/scale-network#519]
## Description

Example of the issue (https://gitlab.com/socallinuxexpo/scale-network/-/jobs/3531597453):

```
...
$ bundle exec rake spec TEST_TYPE=openwrt TARGET_HOST=192.168.254.100 | tee ${CI_PROJECT_DIR}/openwrt/work/serverspec.log
/usr/local/bin/ruby27 -I/var/tmp/gitlab_runner/builds/b1SAyN38/0/socallinuxexpo/scale-network/tests/serverspec/.bundle/ruby/2.7/gems/rspec-core-3.11.0/lib:/var/tmp/gitlab_runner/builds/b1SAyN38/0/socallinuxexpo/scale-network/tests/serverspec/.bundle/ruby/2.7/gems/rspec-support-3.11.0/lib /var/tmp/gitlab_runner/builds/b1SAyN38/0/socallinuxexpo/scale-network/tests/serverspec/.bundle/ruby/2.7/gems/rspec-core-3.11.0/exe/rspec --pattern spec/openwrt/\*_spec.rb
An error occurred while loading ./spec/openwrt/init_spec.rb.
On host `192.168.254.100'
Failure/Error: KERNEL = command("uname -a").stdout.chomp
Errno::ECONNREFUSED:
  Connection refused - connect(2) for 192.168.254.100:22
  
# ./.bundle/ruby/2.7/gems/net-ssh-7.0.1/lib/net/ssh/transport/session.rb:72:in `initialize'
# ./.bundle/ruby/2.7/gems/net-ssh-7.0.1/lib/net/ssh.rb:250:in `new'
# ./.bundle/ruby/2.7/gems/net-ssh-7.0.1/lib/net/ssh.rb:250:in `start'
# ./.bundle/ruby/2.7/gems/specinfra-2.83.3/lib/specinfra/backend/ssh.rb:82:in `create_ssh'
# ./.bundle/ruby/2.7/gems/specinfra-2.83.3/lib/specinfra/backend/ssh.rb:116:in `ssh_exec!'
# ./.bundle/ruby/2.7/gems/specinfra-2.83.3/lib/specinfra/backend/ssh.rb:17:in `block in run_command'
# ./.bundle/ruby/2.7/gems/specinfra-2.83.3/lib/specinfra/backend/ssh.rb:67:in `with_env'
# ./.bundle/ruby/2.7/gems/specinfra-2.83.3/lib/specinfra/backend/ssh.rb:16:in `run_command'
# ./.bundle/ruby/2.7/gems/specinfra-2.83.3/lib/specinfra/runner.rb:11:in `method_missing'
# ./.bundle/ruby/2.7/gems/serverspec-2.42.0/lib/serverspec/type/command.rb:28:in `command_result'
# ./.bundle/ruby/2.7/gems/serverspec-2.42.0/lib/serverspec/type/command.rb:6:in `stdout'
# ./spec/openwrt/init_spec.rb:6:in `<top (required)>'
No examples found.
Finished in 0.00017 seconds (files took 1.99 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples
/usr/local/bin/ruby27 -I/var/tmp/gitlab_runner/builds/b1SAyN38/0/socallinuxexpo/scale-network/tests/serverspec/.bundle/ruby/2.7/gems/rspec-core-3.11.0/lib:/var/tmp/gitlab_runner/builds/b1SAyN38/0/socallinuxexpo/scale-network/tests/serverspec/.bundle/ruby/2.7/gems/rspec-support-3.11.0/lib /var/tmp/gitlab_runner/builds/b1SAyN38/0/socallinuxexpo/scale-network/tests/serverspec/.bundle/ruby/2.7/gems/rspec-core-3.11.0/exe/rspec --pattern spec/openwrt/\*_spec.rb failed
```

This happens if during troubleshooting for the flash coordinator (pi) you accept the host key for the AP while wanting to log into it via SSH. Subsequent CI tests will fail until you remove to host key from `/root/.ssh/known_hosts`. The autoflash test should not honor `/root/.ssh/known_hosts` since these tests are ephemeral by design.

## Acceptance Criteria
- serverspec tests for openwrt do not use host keys
- potentially configure coordinator's openssh client to never check host keys for the autoflash network unless explicitly set

**Comment by owendelong** [comment]
One easy work around for this is to pass OpenSSH client the following argument: -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no"
